version: "3.8"

services:
  yt-dlp-gotelegrambot:
    image: geergon/yt-dlp-gotelegrambot:latest
    volumes:
      - ./downloads:/downloads
    environment:
      APP_ID: ${APP_ID}
      API_HASH: ${API_HASH}
      BOT_TOKEN: ${BOT_TOKEN}
      CHAT_ID: ${CHAT_ID}
