allowed_chat = []
allowed_user = []
auto_download = true
delete_url = true
duration = '600'
live_filter = '!is_live & !was_live'
long_video_download = false
yt-dlp_filter = 'bv[height<=1080][vcodec^=avc1][filesize<500M]+ba[ext=m4a]/bv[height<=720][vcodec^=avc1][filesize<400M]+ba[ext=m4a]/bv[height<=480][vcodec^=avc1][filesize<300M]+ba[ext=m4a]/b[ext=mp4]'
cache_max_age_days = 30
cache_max_size_gb = 10
